### PR TITLE
Docstring/typo fixes

### PR DESCRIPTION
**Pull request by truth-quark**
This is a documentation cleanup PR. Most fixes are docstring formatting for API docs & typos.

### CODE REVIEW

**Comment by jeremyh** [comment]
Thanks Ben, it looks good. The only thing I'm slightly hesitant about are the docstring todos

```
:param cop_pathname:
        TODO.
```

This would have the effect of suppressing the linter warning about missing docstring parameters (if we run one) without the issue being fixed. I'd probably lean toward leaving them off (or fill in the actual text) to keep future linters correctly specific.

**Comment by uchchwhash** [comment]
Looks good. Thanks @truth-quark.

**Review by uchchwhash — APPROVED** [review]

**Comment by truth-quark** [comment]
> Thanks Ben, it looks good. The only thing I'm slightly hesitant about are the docstring todos
> 
> ```
> :param cop_pathname:
>         TODO.
> ```
> 
> This would have the effect of suppressing the linter warning about missing docstring parameters (if we run one) without the issue being fixed. I'd probably lean toward leaving them off (or fill in the actual text) to keep future linters correctly specific.

I've got these as the newly added docstring params:

```Bash
$ grep -rn TODO[.] wagl/
wagl/ancillary.py:611:        TODO.
wagl/ancillary.py:756:        TODO.
wagl/longitude_latitude_arrays.py:105:        TODO.
wagl/satellite_solar_angles.py:40:        TODO.
wagl/satellite_solar_angles.py:933:        TODO.
wagl/hdf5/__init__.py:134:        TODO.
```

There's a few params which I don't have the context to document correctly:

* [ ] cop_pathname
* [ ] offshore
* [ ] depth
* [ ] centre
* [ ] trackpoints

The code docs are missing for some of these. Does anyone know the background for these params?

**Comment by uchchwhash** [comment]
> There's a few params which I don't have the context to document correctly:
> 
> * [ ]  cop_pathname
> * [ ]  offshore
> * [ ]  depth
> * [ ]  centre
> * [ ]  trackpoints
> 
> The code docs are missing for some of these. Does anyone know the background for these params?

That's okay. Thanks for clearly marking them as TODO. That will do.

**Comment by truth-quark** [comment]
> > The code docs are missing for some of these. Does anyone know the background for these params?
> 
> That's okay. Thanks for clearly marking them as TODO. That will do.

Ok, @sixy6e might have background info to help fill in some details too.

**Pull request merged**
